export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_ERROR = 'ERROR_MESSAGE';
export const AUTH_LOADING_STATUS = 'LOADING_STATUS';
export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const LOG_OUT = 'LOG_OUT';
export const CREATE_LOADING_STATUS = 'CREATE_LOADING_STATUS';
export const CREATE_ERROR = 'CREATE_ERROR';
export const GET_ALL_ERROR = 'GET_ALL_ERROR';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const GET_SINGLE_REQUEST = 'GET_SINGLE_REQUEST';
export const SINGLE_REQUEST_ERROR = 'SINGLE_REQUEST_ERROR';

