export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const LOADING_STATUS = 'LOADING_STATUS';
export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS';
export const CREATE_REQUEST = 'CREATE_REQUEST';
